name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: |
          echo "your_docker_password" | docker login -u "your_docker_username" --password-stdin

      - name: Build Docker image
        run: docker build -t "your_docker_username/my-app:latest" .

      - name: Push Docker image to Docker Hub
        run: docker push "your_docker_username/my-app:latest"

      - name: Use Minikube Docker daemon
        run: |
          & minikube -p minikube docker-env --shell powershell | Invoke-Expression

      - name: Deploy to Minikube
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
