name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "DockerAb26." | docker login -u "abubakaraly" --password-stdin

      - name: Build Docker image
        run: docker build -t abubakaraly/my-app:latest .

      - name: Push Docker image to Docker Hub
        run: docker push abubakaraly/my-app:latest

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: |
          minikube start --driver=docker
          kubectl config use-context minikube

      - name: Deploy to Minikube
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
