name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout your repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Connect local Docker CLI to Minikube's Docker daemon
      - name: Use Minikube Docker daemon (PowerShell-compatible)
        shell: powershell
        run: |
          & minikube -p minikube docker-env --shell powershell | Invoke-Expression

      # Step 3: Debug Secret Access (Optional, but helpful for troubleshooting)
      - name: Debug Secret Access (safe version)
        shell: bash
        run: |
          if [ -n "${{ secrets.DOCKER_USERNAME }}" ]; then echo "USERNAME set"; else echo "USERNAME missing"; fi
          if [ -n "${{ secrets.DOCKER_PASSWORD }}" ]; then echo "PASSWORD set"; else echo "PASSWORD missing"; fi

      # Step 4: Log in to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 5: Build the Docker image using Minikube's Docker daemon
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .

      # Step 6: (Optional) Push to Docker Hub if needed
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      # Step 7: Deploy the application to Minikube
      - name: Deploy to Minikube
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
